version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          - LOCALE: ja
          - LANG: ja_JP.UTF-8
          - TZ: Asia/Tokyo

    working_directory: ~/.project

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install task-japanese
      - run: echo 'ja_JP.UTF-8 UTF-8' | sudo tee -a  /etc/locale.gen
      - run: sudo locale-gen
      - run: sudo update-locale LANG=ja_JP.UTF-8

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "build.gradle" }}
            - dependency-cache-

      - save_cache:
          key: dependency-cache-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - run: java -version
      - run: chmod +x gradlew
      - run: ./gradlew cleanAll
      - run: ./gradlew unitTest

      - store_artifacts:
          path: ~/.project/build/reports/
          destination: test_results

workflows:
  version: 2
  test:
    jobs:
    - build:
        filters:
          branches:
            only: feature/java8-gradle3
