version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:10.0.2-jdk-browsers
        environment:
          - LOCALE: ja
          - LANG: ja_JP.UTF-8
          - TZ: Asia/Tokyo
          - CIRCLE_TEST_REPORTS: /tmp/test-results

    working_directory: ~/.project

    steps:
      - checkout
      - run:
          name: locale settings
          command: |
            sudo apt update
            sudo apt install task-japanese
            echo 'ja_JP.UTF-8 UTF-8' | sudo tee -a /etc/locale.gen
            sudo locale-gen
            sudo update-locale LANG=ja_JP.UTF-8

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "build.gradle" }}
            - dependency-cache-

      - save_cache:
          key: dependency-cache-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - run:
        name: run unit test
        command: |
          java -version
          chmod +x gradlew
          ./gradlew cleanAll
          ./gradlew unitTest

      - store_artifacts:
          path: ~/.project/build/reports/
          destination: /tmp/test-results

workflows:
  version: 2
  test:
    jobs:
      - test
