version: 2.1

executors:
  jdk8:
    docker:
      - image: circleci/openjdk:8u181-jdk-browsers
        environment:
        - LOCALE: ja
        - LANG: ja_JP.UTF-8
        - TZ: Asia/Tokyo
        - CIRCLE_TEST_REPORTS: /tmp/test-results
        - JACOCO_SOURCE_PATH: src/main/groovy
  jdk11:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-browsers
        environment:
        - LOCALE: ja
        - LANG: ja_JP.UTF-8
        - TZ: Asia/Tokyo
        - CIRCLE_TEST_REPORTS: /tmp/test-results
        - JACOCO_SOURCE_PATH: src/main/groovy

commands:
  coverage:
    steps:
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - deploy:
          name: Send coverage report to Code Climate
          command: |
            ./cc-test-reporter before-build
            ./cc-test-reporter format-coverage --input-type jacoco -d ~/.project/build/reports/coverage/coverageTest/coverageTest.xml
            ./cc-test-reporter upload-coverage

  build_and_testing:
    steps:
      - checkout
      - run:
          name: Locale settings
          command: |
            sudo apt update
            sudo apt install task-japanese
            echo 'ja_JP.UTF-8 UTF-8' | sudo tee -a /etc/locale.gen
            sudo locale-gen
            sudo update-locale LANG=ja_JP.UTF-8

      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "build.gradle" }}
          - dependency-cache-

      - save_cache:
          key: dependency-cache-{{ checksum "build.gradle" }}
          paths:
          - ~/.gradle

      - run:
          name: Run unit test
          command: |
            java -version
            chmod +x gradlew
            ./gradlew cleanAll
            ./gradlew coverageTest

      - store_artifacts:
          name: Create spock report
          path: ~/.project/build/reports/tests/unitTest
          destination: reports/spock

      - store_artifacts:
          name: Create Jacoco coverage report
          path: ~/.project/build/reports/coverage
          destination: reports/coverageTest

      - store_artifacts:
          name: Create test summary
          path: ~/.project/build/reports/tests/unitTest
          destination: /tmp/test-results

jobs:
  test-on-jdk8:
    executor:
      name: jdk8
    steps:
      - build_and_testing
  test-on-jdk11:
    executor:
      name: jdk11
    steps:
      - build_and_testing
      - coverage

workflows:
  version: 2
  test:
    jobs:
      - test-on-jdk8
      - test-on-jdk11
