package jsonlenium.util

enum Message {
    COMPILE_RESULT,
    COMPILE_JSON_NOT_FOUND,
    COMPILE_CREATED_TESTCASE,
    COMPILE_INVALID_TESTCASE,
    COMPILE_INVALID_TESTFILE_URL,
    COMPILE_INVALID_TESTFILE_FORMAT,
    COMPILE_INTERNAL_ERROR,
    COMPILE_INVALID_ATTRIBUTE_SPECIFIDED_ERROR,
    COMPILE_INVALID_ATTRIBUTE_TYPE_ERROR,
    COMPILE_INVALID_ATTRIBUTE_EMPTY_ELEMENT_ERROR,
    COMPILE_INVALID_ATTRIBUTE_VALUE_ERROR,
    COMPILE_INVALID_ATTRIBUTE_REQUIRED_ERROR,
    COMPILE_INVALID_ATTRIBUTE_ANY_REQUIRED_ERROR,
    COMPILE_INVALID_CAUSE_UNDEFINED_ATTRIBUTE,
    COMPILE_INVALID_CAUSE_CASE_SENSITIVE,
    COMPILE_INVALID_CAUSE_HIERARCHY,
    ASSERTION_PATH_NOT_MATCHED_ERROR,
    ASSERTION_RUNTIME_ERROR,
    ASSERTION_REGULAR_EXPRESSION_ERROR,
    ASSERTION_WEBDRIVER_ERROR,
    ASSERTION_EXIST_BROWSER_ERROR,
    ASSERTION_NOT_EXIST_BROWSER_ERROR,
    ASSERTION_PATH_ILLEGAL_ERROR,
    ASSERTION_SUCCESS,
    ASSERTION_FAILURE,
    ASSERTION_RETRY_BROWSER,
    ASSERTION_RETRY_PARSER,
    ASSERTION_RESULT_01,
    ASSERTION_RESULT_02,
    ASSERTION_RESULT_03,
    ASSERTION_RESULT_04,
    ASSERTION_RESULT_05,
    ASSERTION_RESULT_06,
    ASSERTION_RESULT_07,
    ASSERTION_RESULT_08,
    ERROR_FILE_LOCATION

    @Override
    String toString() {
        ResourceBundle.getBundle("messages", Locale.getDefault()).getString(name())
    }
}
